Update pagespeed_insights.yml

diff --git a/.github/workflows/pagespeed_insights.yml b/.github/workflows/pagespeed_insights.yml
--- a/.github/workflows/pagespeed_insights.yml
+++ b/.github/workflows/pagespeed_insights.yml
@@ -60,24 +60,24 @@ jobs:
             exit 1
           fi
 
-      - name: Set commit status to success
-        if: success()
-        env:
-          GITHUB_TOKEN: ${{ secrets.GH_ACTIONS_TOKEN }}
-        run: |
-          COMMIT_SHA=${{ steps.get-sha.outputs.sha }}
-          curl -s -X POST -H "Authorization: token $GITHUB_TOKEN" \
-            -d '{"state": "success", "target_url": "", "description": "PageSpeed Check Passed", "context": "fetch_pagespeed"}' \
-            https://api.github.com/repos/${{ github.repository }}/statuses/$COMMIT_SHA
-          exit 0
+      # - name: Set commit status to success
+      #   if: success()
+      #   env:
+      #     GITHUB_TOKEN: ${{ secrets.GH_ACTIONS_TOKEN }}
+      #   run: |
+      #     COMMIT_SHA=${{ steps.get-sha.outputs.sha }}
+      #     curl -s -X POST -H "Authorization: token $GITHUB_TOKEN" \
+      #       -d '{"state": "success", "target_url": "", "description": "PageSpeed Check Passed", "context": "fetch_pagespeed"}' \
+      #       https://api.github.com/repos/${{ github.repository }}/statuses/$COMMIT_SHA
+      #     exit 0
 
-      - name: Set commit status to failure
-        if: failure()
-        env:
-          GITHUB_TOKEN: ${{ secrets.GH_ACTIONS_TOKEN }}
-        run: |
-          COMMIT_SHA=${{ steps.get-sha.outputs.sha }}
-          curl -s -X POST -H "Authorization: token $GITHUB_TOKEN" \
-            -d '{"state": "failure", "target_url": "", "description": "PageSpeed Check Failed", "context": "fetch_pagespeed"}' \
-            https://api.github.com/repos/${{ github.repository }}/statuses/$COMMIT_SHA
-          exit 1
+      # - name: Set commit status to failure
+      #   if: failure()
+      #   env:
+      #     GITHUB_TOKEN: ${{ secrets.GH_ACTIONS_TOKEN }}
+      #   run: |
+      #     COMMIT_SHA=${{ steps.get-sha.outputs.sha }}
+      #     curl -s -X POST -H "Authorization: token $GITHUB_TOKEN" \
+      #       -d '{"state": "failure", "target_url": "", "description": "PageSpeed Check Failed", "context": "fetch_pagespeed"}' \
+      #       https://api.github.com/repos/${{ github.repository }}/statuses/$COMMIT_SHA
+      #     exit 1
